### ISSUE TITLE
project run time error

### ISSUE THREAD

**Issue by Lekhrajk** [BootstrapDash/StarAdmin-Free-Vue-Admin-Template#9]
Cannot find module 'webpack-cli/bin/config-yargs'
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\rajka\Documents\vue js project\StarAdmin-Free-Vue-Admin-Template\source\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by bootstrapdash-team** [comment]
Hi @Lekhrajk We have fixed this issue and have updated the repo today. Please try again.
